version: '3'

services:
  web: 
    container_name: example
    build: .
    ports:
      - "5002:3000"
    restart: always
    links:
      - mongo
    
  mongo:
    container_name: mymongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: always