apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hellomongo
  namespace: first-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-hellomongo
  template:
    metadata:
      labels:
        app: my-hellomongo
    spec:
      containers:
        - name: my-hellomongo
          image: mvrcentes/first_deployment:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO-ROOT-USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO-ROOT-PASSWORD
            - name: DATABASE_URL
              valueFrom: 
                configMapKeyRef:
                  name: my-mongo-configmap
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: my-hellomongo
  namespace: first-deployment
spec:
  selector:
    app: my-hellomongo
    namespace: first-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000